### ISSUE TITLE
Runtime error when a turf explodes

### ISSUE THREAD

**Issue by Profakos** [SuperSayu/tgstation#106]
I was fixing meteor mode (someone passed an empty list as a potential list of meteors), I was bombarded by multiple copies of this message:

runtime error: Cannot execute null.ChangeTurf().
proc name: New (/obj/structure/faketurf/New)
  source 

file: gravity_decay.dm,116
  usr: 0
  src: the wall (/obj/structure/faketurf)
  call stack:
the wall (/obj/structure/faketurf): New(the wall (81,76,1) 

(/turf/simulated/wall), 0)

This message popped up after every single meteor hit. 
The only change I did to your code was changing /proc/spawn_meteors(var/number = 10, var/list/meteortypes) to /proc/spawn_meteors(var/number = 10, var/list/meteortypes = meteorsA)

---

Tested after reverting changes: bomb explosions that destroy turfs creates this runtime. Faketurf line 116 does a loc:ChangeTurf, but loc is null.

---

Further trace: Ex_act on walls and floors have a chance to create fake turfs. This is what is causing the runtimes. Removed the faketurf creation calls from the explosions: no runtimes or weird behaviour, holes appear and wall ingredients drop accordingly. Fake turf creation for explosions is weird, as they do not move on their own, since there is no singularity to move them.

---

Suggestion: leave faketurf creation to singularity, who actually interacts with them. I have a pull ready for it.

**Comment by SuperSayu** [comment]
I mentioned already in the chat, but for public records sake:

This is a qdel bug; the error is behind a spawn(), and in between the original code and the spawned code, the faketurf gets garbage collected but is not yet deleted.  Before qdel, the object would have been deleted instead and the spawned code would not execute.

Fixing the code as is requires a sanity check in the spawn code to make sure it is not in nullspace.

**Comment by Profakos** [comment]
Issue fixed.
