### ISSUE TITLE
Virology

### ISSUE THREAD

**Issue by SuperSayu** [SuperSayu/tgstation#108]
From Qpmz234:

For the record we got a glitch over here in virology if you isolate Longevity and throw it in the PANDEMIC, the interface blanks out and all you can do is eject or empty, it doesn't show what's in there, or let you make a culture. Repeated many, many times so I'm sure it's a glitch

**Comment by Profakos** [comment]
This is probably be intended. Some virus symtoms have a stealth value, making them be able to hide from even the chemmaster.

**Comment by Profakos** [comment]
I checked the code. Advanced diseases have all their stats start from 1, and then add the component symptom stats to it. Longevity's stealth is 3. If total stealth is above 2, medanalyzer don't detect the virus. If total stealth is above 3, the pandemic won't see the virus either. This is intended behaviour.
EDIT: confirmed by Seiga

**Comment by Profakos** [comment]
Can be closed, issue was a misunderstanding.

**Comment by Profakos** [comment]
@SuperSayu outdated issue
