### ISSUE TITLE
Sec Gasmask Are Mute

### ISSUE THREAD

**Issue by Profakos** [SuperSayu/tgstation#130]
Security gasmasks, instead of playing ROBOCOP QUOTES, mute all sounds. I didn't even know they did a sound until I tested them in a local version of the latest TG repository.
Using them on a local server prompted an access prompt, asking if the game is allowed to read HALTHALTHALT.ogg, so that could be the issue.

**Comment by SuperSayu** [comment]
I don't mind removing theworstquoteever (that horrible profanity-laden thing that is on beepsky and I think also the hailer) but the audible sounds are supposed to be so that you can alert people who don't pay attention to the chat pane.

**Comment by Profakos** [comment]
Rephrased the title to actually say what I meant to say.
I forgot about the horrible beepsky noise, I would be okay with those vanishing.

**Comment by Profakos** [comment]
Update on the issue: using latest Sayucode, they work in a local session. They do not work on the live server, using the same code. Must be a permissions issue?

**Comment by Profakos** [comment]
Resolved.
