### ISSUE TITLE
Vending machines are not dispensing products

### ISSUE THREAD

**Issue by Profakos** [SuperSayu/tgstation#138]
No runtimes. I suspect this line https://github.com/SuperSayu/-tg-station/commit/77a8bd9a9ec9263a17cf7e9c790bd53b30c2a753#diff-be8fc4ef536d83a7c390019dd59d14efR152
E: Scratch that, I am unsure, maybe a problem with loc? Hm.

**Comment by Profakos** [comment]
Reverting the latest change in code/game/machinery/vending.dm worked.
Nature of error: the vending machine was filled with empty datums, that only had a different name, but no referred object to vend.

**Comment by SuperSayu** [comment]
I see it, mistyped a line in my last edit ( https://github.com/SuperSayu/-tg-station/blob/sayustation/code/game/machinery/vending.dm#L11 should be path not type)

**Comment by SuperSayu** [comment]
Fixed https://github.com/SuperSayu/-tg-station/commit/9913598931c763a78869fd167c01bea322013b7e
