### ISSUE TITLE
Nukeops door unopenable

### ISSUE THREAD

**Issue by SuperSayu** [SuperSayu/tgstation#14]
Upstream problem from TG, I dunno what their problem is.

**Comment by Profakos** [comment]
There are seven syndie spawnpoints, two of them inside the ship. The blast door can only be opened by the millitary PDA (inside the ship), and the door opening computer (also inside the ship).
Three nukers spawned outside the ship in the Nuke Dining Room.

EDIT: Jac said it is a Metastation only error.

**Comment by SuperSayu** [comment]
Resolved in 8891d60007b4e17d0b1da7ab3be97ef8a85b3b05 ; no longer an issue after 679b5f1377d90f3542da0fb8569546cf0121646c
