### ISSUE TITLE
Human Speed

### ISSUE THREAD

**Issue by Profakos** [SuperSayu/tgstation#141]
Running and walking speed might need to be decreased by one, as running is so fast, you can dodge lasers and energy beams by running at them. We managed to replicate this many times, it was amazing.

**Comment by SuperSayu** [comment]
We may need to fix projectile can_pass() or cross() whatever the function name is.  The two objects should never be in the same square, no matter who is moving.

**Comment by Profakos** [comment]
Novemmerge will include a fix for projectile's Bump(). It had a pointless Spawn() call, which caused this. People are a bit still fast though, but lets not change it until I merge the nograv speed fixes.

**Comment by Profakos** [comment]
The bump thing was fixed in the merge.
Also: our movespeed is so high there is no difference between Nukeop Suit's slowspace and fastcombat mode during gameplay.

**Comment by SuperSayu** [comment]
Do you recommend changing it in the config file and if so to what

**Comment by Profakos** [comment]
It is a config option in game_options.txt. 
It is supposed to be
RUN_DELAY 1
WALK_DELAY 4
but
RUN_DELAY 0
WALK_DELAY 3
works too. The the 1/4 value is on our repo, but on our server it is set to -1/2.
Probably best to change it to 0/3 for now, we'll see if it needs to further tweaked.

**Comment by Profakos** [comment]
It seems to have been working. Nobody said anything bad about the speed, even the miners in their  hardsuits, who still managed to kill a lot of monsters. Issue resolved.
