### ISSUE TITLE
Virus seeds

### ISSUE THREAD

**Issue by Profakos** [SuperSayu/tgstation#144]
The smartfridges check for the name of the items in them instead of their type paths, therefore if you name a virus culture, pills or bottle as  something that includes "seeds" or "mycellum", you can vend them in a plastic bag, also creating runtimes, but still putting them in the bag.

**Comment by SuperSayu** [comment]
pfffffthahaha

my bad, I'll look into it

**Comment by Profakos** [comment]
Please wait a bit, as Grand Merge July moves the biogenerator code. (I am almost done with it though)
