### ISSUE TITLE
Bonebots

### ISSUE THREAD

**Issue by Profakos** [SuperSayu/tgstation#145]
Reminder to me about a reported issue about my code from earlier: The game tries to break the bones of mobs that are without them, runtimeing.

**Comment by Profakos** [comment]
Thinking about the issue more deeply, the bone use check in the defense code is superflous, because the human attack already checks if the attacker's arm hurts. I will either remove the proc call, or replace it one that makes the targetted limb of the hit person ache, if it is broken and the RNG says so.

**Comment by Profakos** [comment]
Sayu, could you help me out? Which line was the runtime called again? I forgot and I can not uncover the rogue line again.

**Comment by SuperSayu** [comment]
I believe you got rid of it in "MOB Absolutes" on March 4:
https://github.com/SuperSayu/-tg-station/commit/7a6f3f7571db9632e1aacd7182b2d2febce60387#diff-d6d8be3f9607785d675a459ea0eceedfL953

**Comment by Profakos** [comment]
I see, thanks

**Comment by Profakos** [comment]
I also see the grab bone check is in a wrong place, I'll fix that too. 
I also probably going to put the bone check somewhere else, because the target_limb and the affecting limb are actually the same limbs: the defenders limbs, so it will never work in this side of the code, without a long check for bones.

**Comment by Profakos** [comment]
Fixed and replaced in the january merge.
