### ISSUE TITLE
Bygex [CRITICAL]

### ISSUE THREAD

**Issue by Profakos** [SuperSayu/tgstation#157]
Something is wrong with how ByGex is linked in the compile options, or it was not ticked in. It keeps making this message: Safety violation: tried to use external call() proc name: replacetext (/proc/replacetext), and then defaults to the regular replacetext function.

**Comment by Profakos** [comment]
Note, this issue didn't appear locally.

**Comment by Profakos** [comment]
Perhaps the bin/bygex.dll has to be put on the server too, and it will solve it.

**Comment by Profakos** [comment]
http://www.byond.com/forum/?post=1738657 General reason and solution here. Bygex doesn't work on linux, and maybe the server runs in linux... If this is true, USE_BYGEX has to be commented out in the compile option file.

**Comment by Profakos** [comment]
critical issue a lot of things are unplayable this way

**Comment by SuperSayu** [comment]
Patched sorry
