### ISSUE TITLE
Manual valve invisible

### ISSUE THREAD

**Issue by SuperSayu** [SuperSayu/tgstation#160]
Manual valves currently look like normal pipes - an overlay must be broken.  Probably already fixed on tg.

**Comment by Profakos** [comment]
Hm, didn't notice this last round. I'll examine this.

**Comment by Profakos** [comment]
Manual valves have normal sprites ingame right now. Turning them works too.

**Comment by SuperSayu** [comment]
![image](https://cloud.githubusercontent.com/assets/84720/7127831/cbc76a2c-e217-11e4-9470-2ac817383176.png)
Maybe it's a mapping error.  I do see some east-west valves those are okay.  EDIT: And yes I see constructed ones are okay it is probably just a badly mapped valve.

**Comment by Profakos** [comment]
Fixed in the january merge.

**Comment by Profakos** [comment]
All valves seem to have their icons now.

**Comment by Profakos** [comment]
@SuperSayu outdated issue
