### ISSUE TITLE
Nano UI plague

### ISSUE THREAD

**Issue by Profakos** [SuperSayu/tgstation#169]
For some people, NanoUI stopped working. It is stuck on "initiating...." before loading any templates. Could be no access to the jquery library?

This is not a global issue, and it stopped working for some people whom it worked before, even though there was no code update. Even after code update, the code is identical. Is the nano library on the server properly?

**Comment by Profakos** [comment]
20:09   Dalm    NanoUI works locally
20:09   ProfessorLizzard    good
20:10   Dalm    let me connect to sayustation to make sure it's still broken for me online
20:11   Dalm    damn
20:11   Dalm    it's not broken online any more
20:11   Dalm    which means that my observation locally isn't worth anything
20:12   ProfessorLizzard    no, it means your client cached it
20:12   ProfessorLizzard    and it is not broken for me, anom, seiga and collen because we visited seiga's test server
20:12   ProfessorLizzard    and I visited mine too
20:12   ProfessorLizzard    _MYSTERY_
20:12   ProfessorLizzard    _SOLVED_

**Comment by Profakos** [comment]
So yeah basically, Nano files were changed to be stored on the server instead of bundled with the resources. The Nano folder with the javascripts and libraries. 
They used to be bundled in the resources, but they were now moved serverside. I am sorry, this is my fault for not noticing and alerting you.

**Comment by SuperSayu** [comment]
Should be fixed
