### ISSUE TITLE
String folder not uploaded

### ISSUE THREAD

**Issue by Profakos** [SuperSayu/tgstation#171]
string folder, containing NPC_chatter and Ion_laws is probably not uploaded. The lack of NPC_chatter crashed the master controller (at least the failsafe controller restarted it)
All instrument sounds seem to be missing. The folder changed when the guitar was added, that might be it. This is not critical server issue though.

**Comment by SuperSayu** [comment]
The strings folder was uploaded.

The sound folder is already a match for what is in the repo, I copied over the repo's version into the station update git and the only changes were the guitar sounds and a couple other minor files.

**Comment by Profakos** [comment]
Strange. I am not sure what the problem could be as no runtime happened according to the logs, and the instruments worked locally.

**Comment by Profakos** [comment]
Current missing files found: config/names/mime.txt

**Comment by SuperSayu** [comment]
I would mime a file being uploaded but sadly I cannot do that in text.

**Comment by Profakos** [comment]
Perhaps :clipboard: :arrow_right: :file_folder:  ?

**Comment by Profakos** [comment]
Instruments missing solved: someone made hearing instruments default to off, it can be set in preferences.
