### ISSUE TITLE
Ankh Master Controller

### ISSUE THREAD

**Issue by Profakos** [SuperSayu/tgstation#172]
In the current version, dieing with an Ankh makes the master controller get stuck in an infinite loop.

**Comment by Profakos** [comment]
The cause is that the Revive() proc calls the damage type setting procs. Each of these, after setting the damages, calls handle_regular_status_updates. This proc is responsible for declaring someone dead or alive, and setting sleeping and unconsciousness. The game checks if you are alive right now. If this is true, and you have enough damage to die, this proc calls Death(), therefore, causing an infinite loop.

Why it isn't causing a problem in other cases:
If revive is called while alive, when you are healed, you won't die again.
When it is called while dead, since handle_regular_status_updates checks for your living status, which doesn't call death() if you are dead. Revive changes your stat change CONSCIOUS at the end of the call.

Solutions:
- Move artifact code out of death() and into the process() of ankh, and add checks for it to only activate if is worn by someone, and not when it is put on a dead corpse. Best, OO solution that we should be using.
- Change your stat to DEAD before calling revive. Possibly Dangerous With Unforeseen Consequences.

**Comment by SuperSayu** [comment]
That infinite loop should be causing recursion runtimes, but whatever, good catch.

I would be hesitant to leave it to process() because that causes a race condition with anything else that is watching for eg dead antagonists; you have no idea what will process first.  Probably just set stat to DEAD before immediately calling revive, or possibly rearrange the order of the functions in revive to eliminate the problem?

**Comment by Profakos** [comment]
It does cause recursion runtimes, the same kind we saw with the Exit runtimes.

The problem with rearranging is that death() returns with the return value of the parent proc, se we can not put if after it. Changing the STAT can work, and is an easy fix but I am still on the fence about it, since that also has unknowns. We should test this version first I guess, if it doesn't cause major problems it can work.

**Comment by Profakos** [comment]
This one can not be fixed by setting the stat, as with sufficiently low amount of health, death() is called every tick. The only result of setting the stat value was making the player get ankhed, gain wings, die again and loose said wings in one hilarious seconds.
Moving the code beyond the declaration of death didn't work either.
Other problem: a 4 minute long spawn in a code that is called every tick and wants to return with a value doesn't sound like a good idea. This all has to go to the Process() of the ankh and the wings, respectively (the protection of the elements thing should be started by the wing after equipped)

**Comment by Profakos** [comment]
Closing this for now, as the crash is solved. Making it work again falls under the Artifact Optimalization issue.
