### ISSUE TITLE
Darker noses and tails

### ISSUE THREAD

**Issue by Profakos** [SuperSayu/tgstation#180]
@CollenN please fix the nose and tail colours in mutantbodyparts, they are darker then our lizard greyscales

**Comment by CollenN** [comment]
I already did this. https://github.com/SuperSayu/-tg-station/pull/165

**Comment by Profakos** [comment]
Yes, but tail wagging was added. You have to do it again.

**Comment by Profakos** [comment]
This has to be done later, because Super Custom Lizards were merged

**Comment by Profakos** [comment]
yeah this would be just too much work to be kept lighter with the amount of custom lizard sprites
