### ISSUE TITLE
You can slip on banana cream bullet casings with no gravity

### ISSUE THREAD

**Issue by Profakos** [SuperSayu/tgstation#194]
Inconsistent with every other slipping things

**Comment by SuperSayu** [comment]
That sounds like it was a fun round

**Comment by Profakos** [comment]
Reason found: banana creme stuns and weakens directly instead of calling M.slip(stun, weaken, src)

**Comment by SuperSayu** [comment]
Yeah, those slip helpers were put in after I wrote the code and it was never updated.  Sorry.

**Comment by Profakos** [comment]
It is okay, this was found in sandbox, so didn't cause any problems.
