### ISSUE TITLE
Space Transitions Problem

### ISSUE THREAD

**Issue by Profakos** [SuperSayu/tgstation#207]
Space transitions are not working again on the server, they work locally.
It is probably a bygex issue again. Is the Linux Bygex up to date?

Although the other bygex related things, namely the ID machine seems to be working?

Or is the server updated to Byond 509?

**Comment by SuperSayu** [comment]
I forgot to upload the relevant config file.  This should be fixed next reboot.

**Comment by Profakos** [comment]
Fixed now.
