### ISSUE TITLE
Secrets Of Trashmail

### ISSUE THREAD

**Issue by Profakos** [SuperSayu/tgstation#21]
Unlabelled parcels are _not_ supposed to end up on the trash sorting conveyor belt, but next to the disposals outlet with Mail written on their windoor. Apparently this is a bug, but nobody has reported it ever.

Source: This post and the answers to it http://www.ss13.eu/phpbb/viewtopic.php?f=3&t=226&start=20#p5824

EDIT: this goes deeper, on Metastation, unlabelled parcels disappear. Or at least, don't go to either disposals in the cargo office at all. 

EDIT2: It ALMOST works in metastation, but the sorting pipe spits it out the wrong way into the maint corridor behind it. 

EDIT3: Tagged the sorting pipe with a destination tagger: now everything thrown into it goes to the mail disposal instead of the conveyor belt. Truly baffling. Anyways, final conclusion: for some reason, when the parcel enters the purposedly filterless sorting pipe, it is shot the other way. When I flipped the pipe, thinking it might be a sprite error, it was still shooting the other way, however, this time it was the correct direction.

**Comment by SuperSayu** [comment]
There is a special sort of sort junction that's supposed to go in that place--Metatstation doesn't have it, but tgstation does.  It's supposed to sort out all wrapped packages.

However, the code doesn't tag wrapped packages as being wrapped, when it should.  I think.  I'll have to test it.

**Comment by SuperSayu** [comment]
Should be fixed by 07f4f7d02ca7242b584abc7b4a385025728756ec ; if it isn't, let me know
