### ISSUE TITLE
Space Meadow in Theater Holodeck

### ISSUE THREAD

**Issue by Profakos** [SuperSayu/tgstation#214]
The lush grass theater stage is made of space tiles instead of holograss tiles.
This should be probably fixed seperately quickly before games, but I'll also include a fix for it in the octomerge.

**Comment by SuperSayu** [comment]
...there's no reason why a theater stage should have changed.  I guess I must have used a different path for holoturf/grass in my pr for tgstation, and when editing our Z2 you or I replaced all the old holograss with a bad path?  That would make DM remove it.

I will push a fix to the server right away

**Comment by Profakos** [comment]
Yeah, there was a different path for holospace turfs too. I guess I should have been more vigilant while I was updating.
