### ISSUE TITLE
No Sayu Species

### ISSUE THREAD

**Issue by Profakos** [SuperSayu/tgstation#215]
sayustation species were not added to the config files on the server. For the needed lines, check the repo.

**Comment by SuperSayu** [comment]
from the current config file:
 ## Races for sayustation
ROUNDSTART_RACES xenoid
ROUNDSTART_RACES plant

**Comment by Profakos** [comment]
Works for me during local testing.

**Comment by Profakos** [comment]
It is strange, since flies clearly work. Can't access it from the config debugging on-server: the roundstart species list empties after after setting up. I can only debug it locally, but there it seems to work.

**Comment by Profakos** [comment]
Later today I'll check the ID of those species datums on the server, if Xenoids are called 'xenoid' and Chlorophites are called 'plant' it should be working

**Comment by Profakos** [comment]
Is there a way to see the contents of var/global/list/roundstart_species[0] while viewing vars

**Comment by SuperSayu** [comment]
To my knowledge you can't reach global variables like that, no

**Comment by SuperSayu** [comment]
I failed to update the binary my bad
