### ISSUE TITLE
Odysseus Sleeper Overpowered

### ISSUE THREAD

**Issue by SuperSayu** [SuperSayu/tgstation#22]
There is no way out of an Odysseus sleeper at all.  Perhaps the freedom implant, or something else?  Or letting people go when power is disabled?

**Comment by Profakos** [comment]
Letting people go when it is disabled. It already looses power in very few minutes if someone is loaded up.

**Comment by Profakos** [comment]
Oh you already did and fixed this, sorry.

**Comment by SuperSayu** [comment]
Don't be sorry, it's my duty to mark it done.

Addressed in d7e082521bae68d87c855c79d29aa79c8e97938e but probably not finished.
