### ISSUE TITLE
Double-wide door click fail

### ISSUE THREAD

**Issue by SuperSayu** [SuperSayu/tgstation#26]
Objects and structures that are larger than one tile fail a basic assumption of the standard ss13 click code, which is that you can determine distance based on their loc.  To wit, the double wide door (whose canonical location is the left panel) cannot be clicked on when you are one square right of the right panel.  Even though you are logically adjacent, it sees you as two squares distant from the object.  Any plans to make objects or creatures larger than 1x1 tiles will have a similar problem.

Getting rid of this bug necessarily requires rewriting the atom/DblClick() code.

**Comment by Profakos** [comment]
You can actually walk through the right half of the double door when it is closed.

**Comment by SuperSayu** [comment]
I could have sworn that was fixed in the version that's live now.

the cause of that is the door's bounding box not being double-wide, which is a simple variable change (bound_width).  This tells byond to treat the item as a multiple-tile entity, which is when the locs list starts to have multiple entries.  The singularity, for example, does not do this; it is a 1x1 object with a large icon, and byond thinks it only takes up one tile.

**Comment by Profakos** [comment]
Nevermind, I noticed it while working in older branches. On the live version it doesn't apply.

**Comment by SuperSayu** [comment]
fixed 6207e84a29c63ad918258dc032f4fd198ca1efc4
