### ISSUE TITLE
Too many traitor objectives

### ISSUE THREAD

**Issue by Profakos** [SuperSayu/tgstation#4]
10 telecrystals is only enough for so much. It should be two thefts/kills plus an escape objective at max.

**Comment by SuperSayu** [comment]
Part of the problem is that extra telecrystals often doesn't help.  Except for a few consumables, the goods used for one heist can be used on the next.  I'm thinking the Emag specifically, but also some of the others.

Granted, kill objectives change that; those tools tend to be used up more.  But you don't get a large number of kill objectives the way you do steal objectives.

**Comment by Profakos** [comment]
However, the problem with too many steal objectives is that if you have to rob several part of the station, lets says, both the CMO and the CE's office, it will be quite harder to avoid detection, especially because you will be really, really absent from your workplace.
Not to mention that if someone wants to use a C4 or EMPgrenades instead of an Emag to break in somewhere, that would be an repeatable act, forcing them to use a single solution, whereas with single thefts, they could validly use multiple strategies.

Also, you will need to get the shuttle called to end the round, that is part of the job of an antagonist. Increased number of objectives will delay this, and as you use up your TCs, you will soon run out of things to use to call the shuttle. It will be especially hard if you get two items to steal that won't fit in your backpack.

I maintain that 4 steal objectives is ridiculous, and forces you to steal access, AND to leave fingerprints everywhere, shortening your lifespan dramatically. I propose that instead of 3-4 steal objectives, it should be 1-2 again, and you could implement the hard mode button instead. Alternatively, make it scale with the number of players: if you have more than 10 player, the max would be the base amount.

The Optional Hard Mode button would be a better idea, since this setup heavily favours veterans, and could discourage new players who have no idea where those items are. The button could be snuck into the define flags, in the gameplay prefs option next to "Be Traitor" and such.

Also if the Syndicate Balloon is still in game as an objective, you don't want to torment the poor soul who got it with three more objectives to steal/kill > .>

**Comment by Profakos** [comment]
Continued/Reposted on the mspaforums, since nobody else has a github account.
