### ISSUE TITLE
Virovending is broken

### ISSUE THREAD

**Issue by Profakos** [SuperSayu/tgstation#40]
22:01   Dalm    ughhhh
22:01   Dalm    the smartfridge in viro is broken
22:02   Selinatjee  :c
22:02   ProfessorLizzard    What happened with it, Dalm?
22:02   Dalm    I can't take out one of my cultures
22:02   ProfessorLizzard    which one?
22:03   Dalm    cough+necro :c
22:03   ProfessorLizzard    huh
22:03   Dalm    it is just stuck in there
22:03   ProfessorLizzard    I'll put the bugs in the bug list on sayugithub
22:03   Dalm    maybe it is because I tried using synaptizine on a sample from it?
22:05   ProfessorLizzard    oh wait dalm
22:05   ProfessorLizzard    there is just no power
22:05   Dalm    no
22:05   Dalm    I can take out all the other samples
22:05   Dalm    just not that one 

22:19   Dalm    I know what caused it
22:19   Dalm    I added synaptizine
22:19   Dalm    to a sample from that bottle
22:19   Dalm    and for some reason that broke the original bottle
22:21   ProfessorLizzard    huh
22:21   ProfessorLizzard    but
22:22   ProfessorLizzard    that shouldn't change things anymore!
22:22   ProfessorLizzard    weird
22:22   ProfessorLizzard    editing a sample is not supposed to edit all bottles if you spill it into different bottles

**Comment by SuperSayu** [comment]
The smartvend can't fetch samples with a + in the name.  The vend link is an HTML link, where + has some sort of meaning.

The drink vender has a similar problem revolving around ' marks in certain drinks.  I'll look at it.

**Comment by SuperSayu** [comment]
fixed fbf86464701991c77b780a15b09dd33c84a86295
