### ISSUE TITLE
Now you equip, now you don't

### ISSUE THREAD

**Issue by Profakos** [SuperSayu/tgstation#54]
Hitting equip when something is in your hand and your paperdoll is folded up will equip it, but will leave the image in your hand slot, until you click on the "Expand inventory" button.

**Comment by Profakos** [comment]
This seem to be fixed, HOWEVER, the sprites of the quick equipped items won't be visible on the equip paperdoll.

**Comment by SuperSayu** [comment]
Yeah, I just noticed that recently.  Which considering I added the last fix for it, is sort of an oops.  I could have sworn I tested it and it worked though.

**Comment by Profakos** [comment]
This was resolved.
