### ISSUE TITLE
Carbon Trails

### ISSUE THREAD

**Issue by Profakos** [SuperSayu/tgstation#73]
Note to self: Make bloody footsteps a proc in carbon, overriden by monkeys and aliens. This should remove the 9 isTypes.

**Comment by SuperSayu** [comment]
As I recall the thing that makes footsteps bloody is a turf var currently, it should go in [blood/oil].Crossed() instead, which is the same way that banana peels make you slip.  See weapons/clown_items for an example.

**Comment by Profakos** [comment]
There has been a progress on this. I have made it use the Crossed proc, and removed the bloody var on turfs.

Still not great enough, there is still place for improvement.

**Comment by Profakos** [comment]
This is now irrevelant with the new footprint system.
