### ISSUE TITLE
Shuttle Emag

### ISSUE THREAD

**Issue by Profakos** [SuperSayu/tgstation#79]
our code: 
if(!emagged && emergency_shuttle.location == DOCKED && user.get_active_hand() == W)

TG code:
if(!emagged && emergency_shuttle.location == 1 && user.get_active_hand() == W)

This should be made similar because the emag didn't work in our version

E:
The DOCKED constant is -1

**Comment by SuperSayu** [comment]
They made the emergency shuttle console a different typepath, which means that fixing it required a map update.  Fixed as of 15438a16b6edd9ab80ca7e362f0810247d615099
